### PR TITLE
Catch and handle UnsupportedVersionException in describeTopicConfigs

### LINKED ISSUE #53: Old version Kafka  compatibility problem
Hey guys, does *Kafdrop* support old version `Kafka 0.10.1.0` ?

The requirements says Kafdrop support Kafka (version 0.10.0 or newer), I tested with compiled `kafdrop-3.19.0-SNAPSHOT.jar`, it seems unsupported (`UnsupportedVersionException` occured )...

Is there any way to let Kafdrop be compatible with old version Kafka ? Something like setting `zookeeper` configurations ?

```plain
...
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is kafdrop.service.KafkaAdminClientException: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.UnsupportedVersionException: The broker does not support DESCRIBE_CONFIGS
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1013)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:645)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at kafdrop.config.CorsConfiguration$1.doFilter(CorsConfiguration.java:88)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
        ...
```

- OS: *`CentOS 7 Linux Kernel 3.10.0-514.16.1.el7.x86_64`*
- JDK: *`OpenJDK 13.0.1-b9`*

### LINKED ISSUE #61: Error "The broker does not support DESCRIBE_CONFIGS"
Description
===========
When using Debezium, which is a Kafka Connect connector, I get the error "The broker does not support DESCRIBE_CONFIGS", when trying to use Event Hub to store schema changes. See Issue #53 which has been closed but, though a workaround (not saving the schema changes) has been found, the problem is still there and prevents a full debezium usage.

How to reproduce
================
Setup Debezium to use EventHub instead of Kafka

Has it worked previously?
=========================
No

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:
 
 - [x] Verified that port 9093 is not blocked by firewall
 - [x] Verified the namespace is either Standard or Dedicated tier (i.e. it is not Basic tier, which isn't supported)
 - [x] Sample you're having trouble with: `Debezium Tutorial`
 - [x] Apache Kafka version: `2.2.0`
 - [x] Kafka client configuration: `none`
 - [x] Namespace and EventHub/topic name
 - [x] Producer failure

### PR DESCRIPTION
**Pull request by conorr**
Fixes #53 using [this solution](https://github.com/obsidiandynamics/kafdrop/issues/53#issuecomment-562234908) recommended by @ekoutanov.

We experience the "broker does not support DESCRIBE_CONFIGS" error using Azure Event Hubs for Kafka. Because it's a managed service we don't have the ability to upgrade the broker.

FWIW Azure is aware of the issue, but haven't given a timeline for a fix https://github.com/Azure/azure-event-hubs-for-kafka/issues/61

### CODE REVIEW

**Comment by ekoutanov** [comment]
Thanks, I'll take a look on Monday.

File: src/main/java/kafdrop/service/KafkaHighLevelAdminClient.java [hunk 1]
```diff
@@ -105,6 +105,9 @@ ClusterDescription describeCluster() {
         configsByTopic.put(entry.getKey().name(), entry.getValue());
       }
     } catch (InterruptedException | ExecutionException e) {
+      if (e.getCause() instanceof UnsupportedVersionException) {
+        return new HashMap<>();
```
Comment (ekoutanov) [inline src/main/java/kafdrop/service/KafkaHighLevelAdminClient.java]: Can you please use `Map.of()`. This is an empty map that does not require mutation.

**Review by ekoutanov — CHANGES_REQUESTED** [review]
